[server]
host = "127.0.0.1"
port = [3000, 8080]

[logger]
level = "debug"

[database]
clean_start = true
url = "sqlite::memory:"

[auth]
secret = "smart-blinds-secret"
expiration = 233333

[external]

[external.default]
type = "Mqtt"
host = "127.0.0.1"
port = 1883
client_id = "client-smart-blinds"
topic = "json/dev/earth"

[mock]
group_name = "sample"
